controller_frequency: 10 # 10 (default and in my udacity class)

TrajectoryPlannerROS:
  max_vel_x: 0.5 # 0.5 (default), 1.0 (in my udacity class)
  min_vel_x: 0.01 # 0.01 (default), -0.1 (in my udacity class)
  max_vel_theta: 2.5 # 1.5 (default), 1.57 (in my udacity class)

  min_in_place_vel_theta: 0.5 # 0.314 (default and in my udacity class)

  acc_lim_theta: 4.0 # 3.14 (default and in my udacity class)
  acc_lim_x: 0.1 # 2.0 (default and in my udacity class)
  acc_lim_y: 0.1 # 2.0 (default and in my udacity class)

  sim_time: 1.0 # 1.0 (default and in my udacity class)

  vx_samples: 5.0 # 5.0 (default and in my udacity class)
  vtheta_samples: 10.0 # 10.0 (default and in my udacity class)

  pdist_scale: 0.6 # 0.6 (default and in my udacity class)
  gdist_scale: 0.8 # 0.8 (default and in my udacity class)
  occdist_scale: 0.02 # 0.02 (default and in my udacity class)

  meter_scoring: true # true (default and in my udacity class)

  holonomic_robot: false # false (default and in my udacity class)
